from app.graph.state import AgentState
from app.utils.logger import get_logger
from app.utils.tracing import add_trace
from app.guardrails.security_rules import SecurityRules

logger = get_logger()

class OutputGuardrails:
    """
    Post-processing validation layer to intercept
    malicious or invalid outputs generated by the LLM
    before they are returned to the user.
    """

    def __init__(self):
        self.rules = SecurityRules()

    def run(self, state: AgentState) -> AgentState:
        """
        Validate generated draft answer.
        """
        draft_answer = state.get("draft_answer", "")

        # If already blocked by input guardrails, skip validation
        if state.get("is_safe") is False:
            return state

        logger.info("Running Output Guardrails")

        is_safe, blocked_reason = self.rules.validate_output(draft_answer)

        if not is_safe:
            logger.warning(f"Output Guardrails blocked generated response. Reason: {blocked_reason}")
            return {
                **state,
                "is_safe": False,
                "blocked_reason": blocked_reason,
                "draft_answer": "The generated response was blocked by security policies.",
                "confidence_score": 0.0,
                "agent_trace": add_trace(state, "output_guardrails", status="blocked")
            }

        logger.info("Output Guardrails passed")
        return {
            **state,
            "is_safe": True,
            "agent_trace": add_trace(state, "output_guardrails", status="passed")
        }
